# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySLwoTX31y1D9CpyqCNRhHNIPhjvSNmj
"""

def kasallik (belgi):
    if belgi=="Isitma":
      return "Parasetamol iching"
    elif belgi=="Bosh oģriģi":
      return "Bolnol iching"
    elif belgi=="Tomoq oģrigi":
      return "Mukaltin iching"
    else:
      return "Shifokorga murojaat qiling"
belgi=input("kasallik belgisini kiriting")
natija=kasallik(belgi)
print (natija)

import pandas as pd

jadval={
"ism":["Manzura", "Ali"],
"familiya":["Mòsinova", "Aliyev"],
"yoshi":[19, 20],
"manzili":["Farğona shahar", "Qòqon shahar"]


}
baza=pd.DataFrame(jadval)
print(baza)

#filtr=baza[baza["yoshi"]<20]
#print(filtr)

#filtr=baza[baza["manzili"]=="Farģona shahar"]
#print(filtr)

#titanik=pd.read_csv("/content/tested (1).csv")
#print(titanik)

#filtr=titanik[titanik['Age']<15]
#print(filtr)

import pandas as pd

jadval={
"ism":["Gulmira", "Ali"],
"familiya":["Abdukarimova", "Aliyev"],
"yoshi":[19, 20],
"manzili":["Farğona shahar", "Qòqon shahar"]


}
baza=pd.DataFrame(jadval)
print(baza)

#filtr=baza[baza["yoshi"]<20]
#print(filtr)

#filtr=baza[baza["manzili"]=="Farģona shahar"]
#print(filtr)

#titanik=pd.read_csv("/content/tested (1).csv")
#print(titanik)

#filtr=titanik[titanik['Age']<15]
#print(filtr)

def kitob_tavsiya(janr):
   if janr == "Detektiv":
      return "Sherlok Xolms kitobini o'qing"
   elif janr == "Romantika":
      return "O'tkan kunlar kitobini o'qing"
   elif janr == "Fantastika":
      return "Garri Potter kitobini o'qing"
   elif janr == "Ilmiy":
      return "Sun'iy intellekt  asoslari kitobini o'qing"
   else:
      return "Kutubxonaga murojaat qiling"
janr = input("Qanday janrdagi kitob kerak? ")
natija = kitob_tavsiya(janr)
print(natija)

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6,250])
y=np.array([0,250,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,0,6,6])
y=np.array([0,250,250,6])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,0,6,6,0])
y=np.array([0,250,250,0,0])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array ([0,0,5,0])
y=np.array([0,200,125,0])
plt.plot(x,y, 'd--y')
plt.show()

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
# Iris datasetini yuklash
iris = load_iris()
X = iris.data
y = iris.target
# Ma'lumotlarni o'qitish va sinov to'plamlariga bo'lish
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.3, random_state=42)
# K-NN modelini yaratish va o'qitish
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
# Sinov to'plamidagi natijalarni baholash
y_pred = knn.predict(X_test)
print(f"K-NN algoritmining aniqligi: {accuracy_score(y_test, y_pred)}")

from sklearn.svm import SVC
# SVM modelini yaratish va o'qitish
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)
# Sinov to'plamida natijalarni baholash
y_pred_svm = svm_model.predict(X_test)
print(f"SVM algoritmining aniqligi: {accuracy_score(y_test,
y_pred_svm)}")

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Iris datasetini yuklash
iris = load_iris()
X = iris.data
y = iris.target

# Ma'lumotlarni o'qitish va sinov to'plamlariga bo'lish
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Logistic Regression modelini yaratish va o'qitish
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# Sinov to'plamida bashorat qilish
y_pred = model.predict(X_test)

# Aniqlikni tekshirish
print("Logistic Regression aniqligi:", accuracy_score(y_test, y_pred))

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Iris datasetini yuklash
iris = load_iris()
X = iris.data
y = iris.target

# Ma'lumotlarni train va testga bo'lish
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# SVM modelini yaratish va o'qitish
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)

# Bashorat qilish
y_pred_svm = svm_model.predict(X_test)

# Aniqlikni hisoblash
print("SVM algoritmining aniqligi:", accuracy_score(y_test, y_pred_svm))

!pip install gtts

from gtts import gTTS
import os
text="Assalomu alaykum hurmatli talabalar"
language="tr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_tr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="tr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_tr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="ru"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ru.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="en"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_en.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="ar"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ar.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="fr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_fr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="zh"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_zh.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="zh-TW"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_zh-TW.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="de"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_de.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="es"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_es.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="ja"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ja.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="ko"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ko.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,1,12,12,1])
y1=np.array([1,7,7,1,1])
x2=np.array([1,12])
y2=np.array([3,3])
x3=np.array([1,12])
y3=np.array([5,5])

x16=np.array([1,1,12,12])
y16=np.array([5,7,7,5])
x17=np.array([1,1,12,12])
y17=np.array([1,3,3,1])
x18=np.array([2])
y18=np.array([6])
x19=np.array([2.5])
y19=np.array([6])
x4=np.array([5])
y4=np.array([6.5])
x5=np.array([4.5])
y5=np.array([6.5])
x6=np.array([4])
y6=np.array([6.5])
x7=np.array([5])
y7=np.array([6.1])
x8=np.array([4])
y8=np.array([6.1])
x9=np.array([3.5])
y9=np.array([6.1])
x10=np.array([4.5])
y10=np.array([6.1])
x11=np.array([5])
y11=np.array([5.7])
x12=np.array([4.5])
y12=np.array([5.7])
x13=np.array([4])
y13=np.array([5.7])
x14=np.array([3.5])
y14=np.array([5.7])
x15=np.array([3])
y15=np.array([5.7])

plt.fill(x16,y16,color='#0099B5')
plt.fill(x17,y17,color='#1EB53A')
plt.plot(x16,y16)
plt.plot(x18,y18,ms=45 ,marker='o', color='white')
plt.plot(x19,y19,ms=45 ,marker='o', color='#0099B5')

plt.plot(x17,y17)

plt.plot(x4,y4,'*',x5,y5,'*',x6,y6,'*',x7,y7,'*',x8,y8,'*',x9,y9,'*',x10,y10,'*',x11,y11,'*',x12,y12,'*',x13,y13,'*',x14,y14,'*',x15,y15,'*',color='white')
plt.plot(x1,y1)

plt.plot(x2,y2,x3,y3,color='#CE1126')
plt.show()

x_bg = np.array([0, 0, 12, 12])
y_bg = np.array([0, 6, 6, 0])
plt.fill(x_bg, y_bg, color='#E30A17')  # Turkiya qizil rangi

theta = np.linspace(0, 2*np.pi, 100)
r_outer = 1.5
r_inner = 1.0
cx, cy = 6, 3

x_outer = chhx + r_outer * np.cos(theta)
y_outer = cy + r_outer * np.sin(theta)

x_inner = cx + r_inner * np.cos(theta)
y_inner = cy + r_inner * np.sin(theta)

plt.fill(x_outer, y_outer, color='white')
plt.fill(x_inner, y_inner, color='#E30A17')  # qizil bilan ichki qirqish

star_cx, star_cy = 7.5, 3  # yulduz markazi
star_r = 0.8

star_angles = np.linspace(0, 2*np.pi, 6)[:-1]  # 5 burchak
x_star = star_cx + star_r * np.sin(star_angles + np.pi/2)
y_star = star_cy + star_r * np.cos(star_angles + np.pi/2)
plt.fill(x_star, y_star, color='white')

plt.axis('equal')
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,1,12,12,1])
y=np.array([1,7,7,1,1])
plt.show()
plt.fill(x,y,color='red')
x1=np.array([2])
y1=np.array([6])
x2=np.array([3.5])
y2=np.array([6.5])
plt.plot(x2,y2,ms=15 ,marker='*', color='yellow')
plt.plot(x1,y1,ms=50 ,marker='*', color='yellow')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([1,1,12,12,1])
y = np.array([1,7,7,1,1])
plt.fill(x, y, color='red')

x1 = np.array([2])
y1 = np.array([6])
plt.plot(x1, y1, ms=50, marker='*', color='yellow')

x2 = np.array([3.5])
y2 = np.array([6.5])
plt.plot(x2, y2, ms=15, marker='*', color='yellow')

x3 = np.array([3.8])
y3 = np.array([5.5])
plt.plot(x3, y3, ms=15, marker='*', color='yellow')

x4 = np.array([3.3])
y4 = np.array(kkk[5.2])
plt.plot(x4, y4, ms=15, marker='*', color='yellow')

plt.axis('equal')
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,1,12,12,1])
y1=np.array([1,7,7,1,1])
x2=np.array([1,12])
y2=np.array([3,3])
x3=np.array([1,12])
y3=np.array([5,5])

x16=np.array([1,1,12,12])
y16=np.array([5,7,7,5])
x17=np.array([1,1,12,12])
y17=np.array([1,3,3,1])
x18=np.array([2])
y18=np.array([6])
x19=np.array([2.5])
y19=np.array([6])
x4=np.array([5])
y4=np.array([6.5])
x5=np.array([4.5])
y5=np.array([6.5])
x6=np.array([4])
y6=np.array([6.5])
x7=np.array([5])
y7=np.array([6.1])
x8=np.array([4])
y8=np.array([6.1])
x9=np.array([3.5])
y9=np.array([6.1])
x10=np.array([4.5])
y10=np.array([6.1])
x11=np.array([5])
y11=np.array([5.7])
x12=np.array([4.5])
y12=np.array([5.7])
x13=np.array([4])
y13=np.array([5.7])
x14=np.array([3.5])
y14=np.array([5.7])
x15=np.array([3])
y15=np.array([5.7])

plt.fill(x16,y16,color='black')
plt.fill(x17,y17,color='yellow')
plt.plot(x16,y16)
plt.plot(x18,y18,ms=45 ,marker='o', color='black')
plt.plot(x19,y19,ms=45 ,marker='o', color='black')

plt.plot(x17,y17)
x_red = np.array([1, 1, 12, 12])
y_red = np.array([3, 5, 5, 3])
plt.fill(x_red, y_red, color='#FF0000') # Sof qizil rang

plt.plot(x4,y4,'*',x5,y5,'*',x6,y6,'*',x7,y7,'*',x8,y8,'*',x9,y9,'*',x10,y10,'*',x11,y11,'*',x12,y12,'*',x13,y13,'*',x14,y14,'*',x15,y15,'*',color='black')

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,1,12,12,1])
y1=np.array([1,7,7,1,1])
x2=np.array([1,12])
y2=np.array([3,3])
x3=np.array([1,12])
y3=np.array([5,5])

x16=np.array([1,1,12,12])
y16=np.array([5,7,7,5])
x17=np.array([1,1,12,12])
y17=np.array([1,3,3,1])
x18=np.array([2])
y18=np.array([6])
x19=np.array([2.5])
y19=np.array([6])
x4=np.array([5])
y4=np.array([6.5])
x5=np.array([4.5])
y5=np.array([6.5])
x6=np.array([4])
y6=np.array([6.5])
x7=np.array([5])
y7=np.array([6.1])
x8=np.array([4])
y8=np.array([6.1])
x9=np.array([3.5])
y9=np.array([6.1])
x10=np.array([4.5])
y10=np.array([6.1])
x11=np.array([5])
y11=np.array([5.7])
x12=np.array([4.5])
y12=np.array([5.7])
x13=np.array([4])
y13=np.array([5.7])
x14=np.array([3.5])
y14=np.array([5.7])
x15=np.array([3])
y15=np.array([5.7])

plt.fill(x16,y16,color='white')
plt.fill(x17,y17,color='red')
plt.plot(x16,y16)
plt.plot(x18,y18,ms=45 ,marker='o', color='white')
plt.plot(x19,y19,ms=45 ,marker='o', color='white')

plt.plot(x17,y17)
x_red = np.array([1, 1, 12, 12])
y_red = np.array([3, 5, 5, 3])
plt.fill(x_red, y_red, color='blue')

plt.plot(x4,y4,'*',x5,y5,'*',x6,y6,'*',x7,y7,'*',x8,y8,'*',x9,y9,'*',x10,y10,'*',x11,y11,'*',x12,y12,'*',x13,y13,'*',x14,y14,'*',x15,y15,'*',color='white')

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,1,12,12,1])
y1=np.array([1,7,7,1,1])
x2=np.array([1,12])
y2=np.array([3,3])
x3=np.array([1,12])
y3=np.array([5,5])

x16=np.array([1,1,12,12])
y16=np.array([5,7,7,5])
x17=np.array([1,1,12,12])
y17=np.array([1,3,3,1])
x18=np.array([2])
y18=np.array([6])
x19=np.array([2.5])
y19=np.array([6])
x4=np.array([5])
y4=np.array([6.5])
x5=np.array([4.5])
y5=np.array([6.5])
x6=np.array([4])
y6=np.array([6.5])
x7=np.array([5])
y7=np.array([6.1])
x8=np.array([4])
y8=np.array([6.1])
x9=np.array([3.5])
y9=np.array([6.1])
x10=np.array([4.5])
y10=np.array([6.1])
x11=np.array([5])
y11=np.array([5.7])
x12=np.array([4.5])
y12=np.array([5.7])
x13=np.array([4])
y13=np.array([5.7])
x14=np.array([3.5])
y14=np.array([5.7])
x15=np.array([3])
y15=np.array([5.7])

plt.fill(x16,y16,color='red')
plt.fill(x17,y17,color='green')
plt.plot(x16,y16)
plt.plot(x18,y18,ms=45 ,marker='o', color='red')
plt.plot(x19,y19,ms=45 ,marker='o', color='red')

plt.plot(x17,y17)
x_red = np.array([1, 1, 12, 12])
y_red = np.array([3, 5, 5, 3])
plt.fill(x_red, y_red, color='white')

plt.plot(x4,y4,'*',x5,y5,'*',x6,y6,'*',x7,y7,'*',x8,y8,'*',x9,y9,'*',x10,y10,'*',x11,y11,'*',x12,y12,'*',x13,y13,'*',x14,y14,'*',x15,y15,'*',color='red')

plt.show()

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=50,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Bagging aniqligi:", accuracy_score(y_test, y_pred))

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

data = load_wine()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Random Forest aniqligi:", accuracy_score(y_test, y_pred))

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = AdaBoostClassifier(
    n_estimators=50,
    learning_rate=1.0,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("AdaBoost aniqligi:", accuracy_score(y_test, y_pred))

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

data = load_digits()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Gradient Boosting aniqligi:", accuracy_score(y_test, y_pred))

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model1 = DecisionTreeClassifier(random_state=42)
model2 = KNeighborsClassifier()
model3 = LogisticRegression(max_iter=1000)

voting_model = VotingClassifier(
    estimators=[
        ('tree', model1),
        ('knn', model2),
        ('logistic', model3)
    ],
    voting='hard'
)

voting_model.fit(X_train, y_train)

y_pred = voting_model.predict(X_test)

print("Voting Classifier aniqligi:", accuracy_score(y_test, y_pred))

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score

data = load_wine()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = ExtraTreesClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Extra Trees aniqligi:", accuracy_score(y_test, y_pred))

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

estimators = [
    ('knn', KNeighborsClassifier()),
    ('tree', DecisionTreeClassifier())
]

model = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression()
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Stacking aniqligi:", accuracy_score(y_test, y_pred))

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = HistGradientBoostingClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Hist Gradient Boosting aniqligi:",
      accuracy_score(y_test, y_pred))

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

data = load_digits()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = VotingClassifier(
    estimators=[
        ('lr', LogisticRegression(max_iter=2000)),
        ('gnb', GaussianNB()),
        ('svc', SVC(probability=True))
    ],
    voting='soft'
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Soft Voting aniqligi:",
      accuracy_score(y_test, y_pred))

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

base_model = KNeighborsClassifier()

model = BaggingClassifier(
    estimator=base_model,
    n_estimators=20,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Bagging + KNN aniqligi:",
      accuracy_score(y_test, y_pred))

from sklearn.ensemble import IsolationForest
from sklearn.datasets import load_iris
import pandas as pd

data = load_iris()

X = data.data

model = IsolationForest(
    n_estimators=100,
    contamination=0.1,
    random_state=42
)

model.fit(X)

predictions = model.predict(X)

df = pd.DataFrame(X)
df["Natija"] = predictions

print(df.head())

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

data = fetch_california_housing()

X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)

print("Xatolik (MSE):", mse)

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

X, y = make_regression(
    n_samples=1000,
    n_features=10,
    noise=0.1,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import mean_squared_error

X, y = make_regression(
    n_samples=500,
    n_features=5,
    noise=10,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = AdaBoostRegressor(
    n_estimators=50,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

housing = fetch_california_housing()

X = housing.data
y = housing.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", r2)

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Real Values")
plt.ylabel("Predicted Values")
plt.title("Random Forest Regressor")
plt.show()

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

X, y = make_regression(
    n_samples=1000,
    n_features=10,
    noise=0.1,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", r2)

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Real Values")
plt.ylabel("Predicted Values")
plt.title("Gradient Boosting Regressor")
plt.show()

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

X, y = make_regression(
    n_samples=1000,
    n_features=10,
    noise=0.1,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = AdaBoostRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", r2)

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Real Values")
plt.ylabel("Predicted Values")
plt.title("AdaBoost Regressor")
plt.show()

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

data = load_iris()

X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

models = {
    "Decision Tree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier()
}

accuracies = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)
    print(name, "Accuracy:", acc)

plt.figure(figsize=(8,6))
plt.bar(models.keys(), accuracies)
plt.xlabel("Classification Methods")
plt.ylabel("Accuracy")
plt.title("Classification Methods Accuracy Comparison")
plt.xticks(rotation=15)
plt.show()

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

X, y = make_regression(
    n_samples=1000,
    n_features=10,
    noise=0.1,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(),
    "AdaBoost": AdaBoostRegressor(),
    "Gradient Boosting": GradientBoostingRegressor()
}

mse_values = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    mse_values.append(mse)
    print(name, "MSE:", mse)

plt.figure(figsize=(8,6))
plt.bar(models.keys(), mse_values)
plt.xlabel("Regression Methods")
plt.ylabel("MSE")
plt.title("Regression Methods MSE Comparison")
plt.xticks(rotation=15)
plt.show()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

np.random.seed(42)
n = 1000
gender = np.random.choice(['ayol', 'erkak'], n)
skol_kredit = np.random.normal(600, 100, n)
daromad = np.random.normal(3000, 800, n)

skol_kredit = np.where(gender == 'ayol', skol_kredit - 50, skol_kredit)
daromad = np.where(gender == 'ayol', daromad - 300, daromad)

tolov_qobilyati = ((skol_kredit > 550) & (daromad > 2500)).astype(int)

df = pd.DataFrame({'jins': gender, 'skor_kredit': skol_kredit, 'daromad': daromad, 'tolov_qobilyati': tolov_qobilyati})
df = pd.get_dummies(df, columns=['jins'], drop_first=True)

X = df.drop('tolov_qobilyati', axis=1)
y = df['tolov_qobilyati']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Aniqlik:", accuracy_score(y_test, y_pred))
print("Koeffitsiyentlar:", dict(zip(X.columns, model.coef_[0])))

X_test_jins = X_test.copy()
ayollar_test = X_test[X_test['jins_erkak'] == 0]
erkaklar_test = X_test[X_test['jins_erkak'] == 1]

y_test_ayol = y_test[X_test['jins_erkak'] == 0]
y_test_erkak = y_test[X_test['jins_erkak'] == 1]

y_pred_ayol = model.predict(ayollar_test)
y_pred_erkak = model.predict(erkaklar_test)

acc_ayol = accuracy_score(y_test_ayol, y_pred_ayol)
acc_erkak = accuracy_score(y_test_erkak, y_pred_erkak)

print("Ayollar uchun aniqlik:", acc_ayol)
print("Erkaklar uchun aniqlik:", acc_erkak)
print("Farq:", abs(acc_ayol - acc_erkak))

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from fairlearn.metrics import demographic_parity_difference

np.random.seed(42)
n = 1000
gender = np.random.choice(['ayol', 'erkak'], n)
skol_kredit = np.random.normal(600, 100, n)
daromad = np.random.normal(3000, 800, n)

skol_kredit = np.where(gender == 'ayol', skol_kredit - 50, skol_kredit)
daromad = np.where(gender == 'ayol', daromad - 300, daromad)

tolov_qobilyati = ((skol_kredit > 550) & (daromad > 2500)).astype(int)

df = pd.DataFrame({'jins': gender, 'skor_kredit': skol_kredit, 'daromad': daromad, 'tolov_qobilyati': tolov_qobilyati})
df = pd.get_dummies(df, columns=['jins'], drop_first=True)

X = df.drop('tolov_qobilyati', axis=1)
y = df['tolov_qobilyati']
sensitive = df['jins_erkak']

X_train, X_test, y_train, y_test, sens_train, sens_test = train_test_split(X, y, sensitive, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

dp_diff = demographic_parity_difference(y_test, y_pred, sensitive_features=sens_test)
print("Demographic Parity Difference:", dp_diff)

from sklearn.metrics import accuracy_score

X_test_jins = X_test.copy()
y_pred = model.predict(X_test)

ayollar = X_test[X_test['jins_erkak'] == 0]
erkaklar = X_test[X_test['jins_erkak'] == 1]

y_test_ayol = y_test[X_test['jins_erkak'] == 0]
y_test_erkak = y_test[X_test['jins_erkak'] == 1]

y_pred_ayol = model.predict(ayollar)
y_pred_erkak = model.predict(erkaklar)

acc_ayol = accuracy_score(y_test_ayol, y_pred_ayol)
acc_erkak = accuracy_score(y_test_erkak, y_pred_erkak)

print("Ayollar aniqlik:", acc_ayol)
print("Erkaklar aniqlik:", acc_erkak)
print("Farq:", round(abs(acc_ayol - acc_erkak), 4))

X_fair = X.drop('jins_erkak', axis=1)
X_train_f, X_test_f, y_train_f, y_test_f = train_test_split(X_fair, y, test_size=0.2, random_state=42)

model_fair = LogisticRegression()
model_fair.fit(X_train_f, y_train_f)
y_pred_fair = model_fair.predict(X_test_f)

acc_fair = accuracy_score(y_test_f, y_pred_fair)
print("Jins olib tashlangan model aniqlik:", acc_fair)